import { useEffect, useState } from 'react';
import { Plus, Wifi, WifiOff, Timer, Moon, Sun, LogOut, Clock3, MoreHorizontal, ListOrdered } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useLanguage } from '@/context/LanguageContext';
import { useTheme } from '@/context/ThemeContext';
import { useAuth } from '@/context/AuthContext';
import { Logo } from '@/components/Logo';
import type { Branch } from '@/lib/types';
import type { ActiveShiftInfo } from '../../hooks/usePosOrder';
export type PosPanelId = 'orders' | 'tables' | 'kitchen' | null;
interface PosTopBarProps { panel: PosPanelId; onPanel:(p:Exclude<PosPanelId,null>)=>void; counts:{activeOrders:number;occupiedTables:number;kitchenOrders:number;heldOrders:number;deliveryOrders:number;takeawayOrders:number}; branchId:string; branches:Branch[]; canChangeBranch:boolean; onBranchChange:(id:string)=>void; isCashier:boolean; shiftChecked:boolean; activeShift:ActiveShiftInfo|null; onNewOrder:()=>void; onExit:()=>void; }
export function PosTopBar({onPanel,counts,branchId,branches,canChangeBranch,onBranchChange,isCashier,shiftChecked,activeShift,onNewOrder,onExit}:PosTopBarProps){
 const {t,lang}=useLanguage(); const {theme,toggleTheme}=useTheme(); const {user,signOut}=useAuth(); const navigate=useNavigate(); const isAr=lang==='ar';
 const [now,setNow]=useState(()=>new Date()); const [online,setOnline]=useState(typeof navigator!=='undefined'?navigator.onLine:true); const [more,setMore]=useState(false);
 useEffect(()=>{const id=setInterval(()=>setNow(new Date()),30000);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{clearInterval(id);window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);
  return <header className="sticky top-0 z-50 flex min-h-16 items-center gap-2 border-b border-ui-border bg-ui-surface/95 px-3 shadow-ui-sm backdrop-blur md:px-4">
    <div className="flex shrink-0 items-center gap-2"><Logo variant="mark" size={34} tone="auto"/><div className="hidden leading-tight sm:block"><p className="text-sm font-black text-ui-text">Premier</p><p className="text-[9px] font-black uppercase tracking-[.16em] text-ui-accent">{t('pos')}</p></div><button onClick={onNewOrder} data-testid="pos-action-new-order" className="flex min-h-10 items-center gap-1.5 rounded-xl bg-ui-primary px-3 text-xs font-black text-ui-primary-fg shadow-ui-sm transition active:scale-95 hover:bg-ui-primary-hover"><Plus className="h-4 w-4"/><span className="hidden sm:inline">{t('newOrder')}</span></button></div>
    <div className="flex-1"/>
    <div className={`hidden items-center gap-1.5 rounded-xl border px-2.5 py-1.5 text-[10px] font-black xl:flex ${online?'border-ui-success/30 bg-ui-success/10 text-ui-success':'border-ui-danger/30 bg-ui-danger/10 text-ui-danger'}`}>{online?<Wifi className="h-3 w-3"/>:<WifiOff className="h-3 w-3"/>}{online?t('online'):t('offline')}</div>
    <div className="hidden items-center gap-1.5 rounded-xl border border-ui-border bg-ui-page-alt px-2.5 py-1.5 text-[10px] font-bold text-ui-muted lg:flex"><Clock3 className="h-3 w-3 text-ui-subtle"/>{now.toLocaleTimeString(isAr?'ar-EG':'en-US',{hour:'2-digit',minute:'2-digit'})}</div>
    {isCashier&&shiftChecked&&<button onClick={()=>navigate('/shifts')} className={`hidden min-h-9 items-center gap-1.5 rounded-xl border px-2.5 text-[10px] font-black md:flex ${activeShift?'border-ui-success/30 bg-ui-success/10 text-ui-success':'border-ui-warning/30 bg-ui-warning/10 text-ui-warning'}`}><Timer className="h-3 w-3"/>{activeShift?t('open'):t('noOpenShift')}</button>}
    <div className="relative"><button onClick={()=>setMore(v=>!v)} aria-label={isAr?'المزيد':'More'} className="flex min-h-10 min-w-10 items-center justify-center rounded-xl border border-ui-border bg-ui-surface text-ui-muted"><MoreHorizontal className="h-5 w-5"/></button>{more&&<div className="absolute end-0 top-12 z-50 w-64 rounded-2xl border border-ui-border bg-ui-surface p-2 shadow-ui-xl"><div className="mb-1 px-3 py-2 text-xs font-black text-ui-subtle">{isAr?'إجراءات إضافية':'More actions'}</div><button onClick={()=>{onPanel('orders');setMore(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold hover:bg-ui-page-alt"><ListOrdered className="h-4 w-4"/>{t('activeOrders')} {counts.activeOrders>0&&<span className="ms-auto rounded-full bg-ui-primary px-2 py-0.5 text-[10px] text-ui-primary-fg">{counts.activeOrders}</span>}</button><button onClick={()=>{navigate('/shifts');setMore(false)}} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold hover:bg-ui-page-alt"><Timer className="h-4 w-4"/>{isAr?'الوردية':'Shift'}</button>{canChangeBranch&&<><div className="my-1 h-px bg-ui-border"/><div className="px-3 py-2 text-[11px] text-ui-subtle">{isAr?'الفرع':'Branch'}</div><select value={branchId} onChange={e=>{onBranchChange(e.target.value);setMore(false)}} className="w-full rounded-xl border border-ui-border bg-ui-page-alt px-3 py-2 text-sm font-bold text-ui-text">{branches.map(b=><option key={b.id} value={b.id}>{isAr?b.name:(b.name_en||b.name)}</option>)}</select></>}</div>}</div>
    <div className="hidden items-center gap-2 lg:flex"><div className="flex h-8 w-8 items-center justify-center rounded-xl bg-ui-primary text-xs font-black text-ui-primary-fg ring-1 ring-ui-border-strong">{(user?.full_name||user?.email||'?')[0].toUpperCase()}</div><div className="max-w-[120px] leading-tight"><p className="truncate text-[11px] font-black text-ui-text">{user?.full_name||user?.email}</p><p className="text-[9px] text-ui-subtle">{user?.role}</p></div></div>
    <button onClick={toggleTheme} aria-label={isAr?'تغيير المظهر':'Toggle theme'} className="flex min-h-10 min-w-10 items-center justify-center rounded-xl text-ui-muted hover:bg-ui-page-alt">{theme==='light'?<Moon className="h-4 w-4"/>:<Sun className="h-4 w-4"/>}</button><button onClick={onExit} aria-label={isAr?'خروج':'Exit'} className="hidden min-h-10 min-w-10 items-center justify-center rounded-xl text-ui-muted hover:bg-ui-page-alt sm:flex"><LogOut className="h-4 w-4 rotate-180"/></button><button onClick={()=>void signOut()} aria-label={isAr?'تسجيل الخروج':'Sign out'} className="flex min-h-10 min-w-10 items-center justify-center rounded-xl text-ui-subtle hover:bg-ui-danger/10 hover:text-ui-danger"><LogOut className="h-4 w-4"/></button>
  </header>;
}